#!/bin/bash
#©ACSESTECH  raj.atmakuri@acsestech.com

. /usr/share/yinstal/yapi

UIDGIDPAIR=$(findnextpair "system")
groupadd -g $UIDGIDPAIR mysql
useradd -c "MySQL Server" -d /srv/mysql -g mysql -s /bin/false -u $UIDGIDPAIR mysql