#!/bin/bash -e

#©ACSESTESCH  raj.atmakuri@acsestech.com

NAME=${1%-?*}
VERS=${1##?*-}
FILE=$(find /yinsource -iname "$NAME.ybuild")

if [ X$FILE != "X" ];then
	sed -i "s/^VERSION=\".*\"/VERSION=\"$VERS\"/" $FILE
fi

while read
	do
		sed -r -i "s/\b${NAME}-[0-9\.]+\b/${1}/ig" ${REPLY}
	done < <(find /yinsource -iname "*.ybuild")