#!/bin/bash -e

#©ACSESTESCH  raj.atmakuri@acsestech.com

if [ -e ../yinscripts/SystemData ];then
	. ../yinscripts/SystemData
else
	echo "No SystemData file found ..."
	exit 1
fi

(cd ../yinscripts;./ShowSystemData)||true

STARTAT="$1"

while read
	do
		sed -i 's|^\(gettar .*\)$|\nscriptLog "${PKGNAME}-${VERSION}"\n\1|' "$REPLY"
	done < <(find ${yantra}/yinsource/${STARTAT} -iname "*.ybuild")