#!/bin/bash

#©ACSESTECH   raj.atmakuri@acsestech.com

. /usr/share/yinstal/yapi

touch /var/log/clamav/clamd.log /var/log/clamav/freshclam.log
chown -R clamav:clamav /var/lib/clamav /var/log/clamav /var/run/clamav
chmod 771 /var/lib/clamav /var/log/clamav /var/run/clamav
chmod 0660 /var/lib/clamav/*
chmod 660 /var/log/clamav/clamd.log /var/log/clamav/freshclam.log

#update db
freshclam
